import type { AgentMedia } from '../types';
import { getAccessToken } from '../auth';
import { API_URL, authFetch } from './client';

export async function getAgentMedia(agentId: number, mediaType?: string): Promise<AgentMedia[]> {
  const url = mediaType 
    ? `${API_URL}/api/agents/${agentId}/media?media_type=${mediaType}`
    : `${API_URL}/api/agents/${agentId}/media`;
  const res = await authFetch(url);
  if (!res.ok) throw new Error('Failed to fetch agent media');
  return res.json();
}

export interface MediaUploadData {
  name?: string;  // Optional for images/documents - auto-generated by AI
  media_type: 'image' | 'video' | 'document';
  description?: string;
  default_caption?: string;
  original_size?: number;  // Original size before compression
  auto_analyze?: boolean;  // Whether to auto-analyze images (default true)
}

export async function uploadAgentMedia(
  agentId: number,
  file: File,
  data: MediaUploadData,
  onProgress?: (progress: number) => void
): Promise<AgentMedia> {
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    const formData = new FormData();
    formData.append('file', file);
    formData.append('media_type', data.media_type);
    if (data.name) formData.append('name', data.name);
    if (data.description) formData.append('description', data.description);
    if (data.default_caption) formData.append('default_caption', data.default_caption);
    // Use provided original_size (before compression) or file.size
    const originalSize = data.original_size || file.size;
    formData.append('original_size', originalSize.toString());
    // Auto-analyze images by default
    formData.append('auto_analyze', (data.auto_analyze !== false).toString());

    xhr.upload.onprogress = (e) => {
      if (e.lengthComputable && onProgress) {
        onProgress(Math.round((e.loaded / e.total) * 70));
      }
    };

    xhr.onload = () => {
      if (xhr.status >= 200 && xhr.status < 300) {
        onProgress?.(100);
        resolve(JSON.parse(xhr.responseText));
      } else {
        try {
          const error = JSON.parse(xhr.responseText);
          reject(new Error(error.detail || 'Upload failed'));
        } catch {
          reject(new Error('Upload failed'));
        }
      }
    };

    xhr.onerror = () => reject(new Error('Network error'));
    xhr.open('POST', `${API_URL}/api/agents/${agentId}/media`);
    // Add auth header
    const token = getAccessToken();
    if (token) xhr.setRequestHeader('Authorization', `Bearer ${token}`);
    xhr.send(formData);
    
    setTimeout(() => onProgress?.(85), 300);
  });
}

export async function updateAgentMedia(
  agentId: number,
  mediaId: number,
  data: { name?: string; description?: string; default_caption?: string; is_active?: boolean }
): Promise<AgentMedia> {
  const res = await authFetch(`${API_URL}/api/agents/${agentId}/media/${mediaId}`, {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(data),
  });
  if (!res.ok) throw new Error('Failed to update media');
  return res.json();
}

export async function deleteAgentMedia(agentId: number, mediaId: number): Promise<void> {
  const res = await authFetch(`${API_URL}/api/agents/${agentId}/media/${mediaId}`, { method: 'DELETE' });
  if (!res.ok) throw new Error('Failed to delete media');
}
